import type { Achievement } from "@/types";

export const ACHIEVEMENTS: Achievement[] = [
  // ==========================================
  // ONBOARDING / BASICS
  // ==========================================
  {
    id: "first_sip",
    name: "First Sip",
    description: "Open the app for the first time.",
    flavorText: "Welcome to the club. Leave your coat at the door.",
    category: "novice",
    icon: "👋",
    tier: 1,
    condition: { metric: "app_opens", threshold: 1 },
  },
  {
    id: "curious_cat",
    name: "Curious Cat",
    description: "Browse your first recipe.",
    flavorText: "Curiosity didn't kill the cat; it got it tipsy.",
    category: "novice",
    icon: "👀",
    tier: 1,
    condition: { metric: "recipes_browsed", threshold: 1 },
  },
  {
    id: "first_love",
    name: "First Love",
    description: "Heart a cocktail.",
    flavorText: "It's not just a drink, it's a relationship.",
    category: "novice",
    icon: "❤️",
    tier: 1,
    condition: { metric: "hearts_given", threshold: 1 },
  },
  {
    id: "pantry_starter",
    name: "Pantry Starter",
    description: "Add an ingredient to your pantry.",
    flavorText: "You have to start somewhere. Usually with Vodka.",
    category: "novice",
    icon: "🧴",
    tier: 1,
    condition: { metric: "pantry_items_count", threshold: 1 },
  },
  {
    id: "mixologist_apprentice",
    name: "Mixologist Apprentice",
    description: "Complete a prep session.",
    flavorText: "Don't spill it.",
    category: "novice",
    icon: "🎓",
    tier: 1,
    condition: { metric: "recipes_prepped", threshold: 1 },
  },

  // ==========================================
  // BROWSING / DISCOVERY
  // ==========================================
  {
    id: "browser_bronze",
    name: "Window Shopper",
    description: "View 10 recipes.",
    flavorText: "Just looking, thanks.",
    category: "explorer",
    tier: 1,
    icon: "🥉",
    condition: { metric: "recipes_browsed", threshold: 10 },
  },
  {
    id: "browser_silver",
    name: "Menu Reader",
    description: "View 50 recipes.",
    flavorText: "So many choices, so little liver.",
    category: "explorer",
    tier: 2,
    icon: "🥈",
    condition: { metric: "recipes_browsed", threshold: 50 },
  },
  {
    id: "browser_gold",
    name: "Recipe Hunter",
    description: "View 100 recipes.",
    flavorText: "You digest information well.",
    category: "explorer",
    tier: 3,
    icon: "🥇",
    condition: { metric: "recipes_browsed", threshold: 100 },
  },
  {
    id: "browser_platinum",
    name: "Bibliophile",
    description: "View 250 recipes.",
    flavorText: "More reading than drinking at this point.",
    category: "explorer",
    tier: 4,
    icon: "💍",
    condition: { metric: "recipes_browsed", threshold: 250 },
  },
  {
    id: "browser_diamond",
    name: "Walking Encyclopedia",
    description: "View 500 recipes.",
    flavorText: "You could be a bartender.",
    category: "explorer",
    tier: 5,
    icon: "💎",
    condition: { metric: "recipes_browsed", threshold: 500 },
  },
  {
    id: "browser_obsidian",
    name: "The Archivist",
    description: "View 1000 recipes.",
    flavorText: "Did you finish the internet?",
    category: "grind",
    tier: 6,
    icon: "🖤",
    condition: { metric: "recipes_browsed", threshold: 1000 },
  },

  {
    id: "search_party_1",
    name: "Seeking Spirits",
    description: "Perform 10 searches.",
    flavorText: "Find what you love.",
    category: "explorer",
    tier: 1,
    icon: "🔍",
    condition: { metric: "searches_performed", threshold: 10 },
  },
  {
    id: "search_party_2",
    name: "Google of Grog",
    description: "Perform 50 searches.",
    flavorText: "Search history: 'how to impress friends'.",
    category: "explorer",
    tier: 2,
    icon: "🔎",
    condition: { metric: "searches_performed", threshold: 50 },
  },

  {
    id: "filter_fanatic",
    name: "Picky Drinker",
    description: "Use filters 20 times.",
    flavorText: "Knowing what you want is a virtue.",
    category: "explorer",
    tier: 1,
    icon: "🌪️",
    condition: { metric: "filters_used", threshold: 20 },
  },

  // ==========================================
  // PANTRY / COLLECTION
  // ==========================================
  {
    id: "hoarder_1",
    name: "Stocking Up",
    description: "Own 5 unique ingredients.",
    flavorText: "A humble beginning.",
    category: "explorer",
    tier: 1,
    icon: "📦",
    condition: { metric: "pantry_items_count", threshold: 5 },
  },
  {
    id: "hoarder_2",
    name: "Home Bar",
    description: "Own 15 unique ingredients.",
    flavorText: "Enough to ruin a Tuesday.",
    category: "explorer",
    tier: 2,
    icon: "🏠",
    condition: { metric: "pantry_items_count", threshold: 15 },
  },
  {
    id: "hoarder_3",
    name: "Well Stocked",
    description: "Own 30 unique ingredients.",
    flavorText: "You can host a party now.",
    category: "master",
    tier: 3,
    icon: "🥂",
    condition: { metric: "pantry_items_count", threshold: 30 },
  },
  {
    id: "hoarder_4",
    name: "Liquor Store",
    description: "Own 50 unique ingredients.",
    flavorText: "Do you have a license for this?",
    category: "master",
    tier: 4,
    icon: "🏬",
    condition: { metric: "pantry_items_count", threshold: 50 },
  },
  {
    id: "hoarder_5",
    name: "Distributor",
    description: "Own 100 unique ingredients.",
    flavorText: "Your liver is scared.",
    category: "grind",
    tier: 5,
    icon: "🏭",
    condition: { metric: "pantry_items_count", threshold: 100 },
  },

  {
    id: "spice_rack",
    name: "Spice of Life",
    description: "Own 5 non-alcoholic ingredients.",
    flavorText: "Mixers matter.",
    category: "explorer",
    icon: "🍋",
    condition: { metric: "pantry_non_alcoholic_count", threshold: 5 },
  },

  // ==========================================
  // PREPPING / MAKING
  // ==========================================
  {
    id: "maker_1",
    name: "Shaker",
    description: "Prep 5 recipes.",
    flavorText: "Shake it off.",
    category: "novice",
    tier: 1,
    icon: "🥤",
    condition: { metric: "recipes_prepped", threshold: 5 },
  },
  {
    id: "maker_2",
    name: "Stirrer",
    description: "Prep 10 recipes.",
    flavorText: "Shaken, not stirred. Or whatever.",
    category: "novice",
    tier: 2,
    icon: "🥄",
    condition: { metric: "recipes_prepped", threshold: 10 },
  },
  {
    id: "maker_3",
    name: "Bartender",
    description: "Prep 25 recipes.",
    flavorText: "Tips not included.",
    category: "explorer",
    tier: 3,
    icon: "🤵",
    condition: { metric: "recipes_prepped", threshold: 25 },
  },
  {
    id: "maker_4",
    name: "Mixologist",
    description: "Prep 50 recipes.",
    flavorText: "It's an art form.",
    category: "master",
    tier: 4,
    icon: "🎨",
    condition: { metric: "recipes_prepped", threshold: 50 },
  },
  {
    id: "maker_5",
    name: "Alchemist",
    description: "Prep 100 recipes.",
    flavorText: "Turning liquid into gold... or headaches.",
    category: "master",
    tier: 5,
    icon: "⚗️",
    condition: { metric: "recipes_prepped", threshold: 100 },
  },
  {
    id: "maker_6",
    name: "Grandmaster",
    description: "Prep 250 recipes.",
    flavorText: "You are the liquor.",
    category: "grind",
    tier: 6,
    icon: "🧙‍♂️",
    condition: { metric: "recipes_prepped", threshold: 250 },
  },
  {
    id: "maker_7",
    name: "Legend",
    description: "Prep 500 recipes.",
    flavorText: "Your photo is on the wall of fame.",
    category: "grind",
    tier: 7,
    icon: "👑",
    condition: { metric: "recipes_prepped", threshold: 500 },
  },
  {
    id: "maker_8",
    name: "Deity",
    description: "Prep 1000 recipes.",
    flavorText: "Immortality through preservation.",
    category: "grind",
    tier: 8,
    icon: "⚡",
    condition: { metric: "recipes_prepped", threshold: 1000 },
  },

  // ==========================================
  // VOLUME / LEDGER
  // ==========================================
  {
    id: "volume_1",
    name: "Hydrated",
    description: "Track 1,000ml of volume.",
    flavorText: "Mostly water, right?",
    category: "novice",
    tier: 1,
    icon: "💧",
    condition: { metric: "total_volume_ml", threshold: 1000 },
  },
  {
    id: "volume_2",
    name: "Thirsty",
    description: "Track 5,000ml of volume.",
    flavorText: "That's 5 liters of... fluid.",
    category: "explorer",
    tier: 2,
    icon: "🌊",
    condition: { metric: "total_volume_ml", threshold: 5000 },
  },
  {
    id: "volume_3",
    name: "Drought Breaker",
    description: "Track 10,000ml of volume.",
    flavorText: "Saving the world from sobriety.",
    category: "master",
    tier: 3,
    icon: "🌧️",
    condition: { metric: "total_volume_ml", threshold: 10000 },
  },
  {
    id: "volume_4",
    name: "The Reservoir",
    description: "Track 50,000ml of volume.",
    flavorText: "You are a camel.",
    category: "grind",
    tier: 4,
    icon: "🐫",
    condition: { metric: "total_volume_ml", threshold: 50000 },
  },
  {
    id: "volume_5",
    name: "Oceanic",
    description: "Track 100,000ml of volume.",
    flavorText: "Please tell me this took years.",
    category: "grind",
    tier: 5,
    icon: "🐋",
    condition: { metric: "total_volume_ml", threshold: 100000 },
  },

  {
    id: "session_1",
    name: "Hosting Duty",
    description: "Complete 5 sessions.",
    flavorText: "Thanks for having us.",
    category: "social",
    tier: 1,
    icon: "🏠",
    condition: { metric: "sessions_completed", threshold: 5 },
  },
  {
    id: "session_2",
    name: "Party Animal",
    description: "Complete 20 sessions.",
    flavorText: "You love a gathering.",
    category: "social",
    tier: 2,
    icon: "🎉",
    condition: { metric: "sessions_completed", threshold: 20 },
  },
  {
    id: "session_3",
    name: "Life of the Party",
    description: "Complete 50 sessions.",
    flavorText: "Where's the afterparty?",
    category: "social",
    tier: 3,
    icon: "🪩",
    condition: { metric: "sessions_completed", threshold: 50 },
  },

  // ==========================================
  // FAVORITES
  // ==========================================
  {
    id: "heart_1",
    name: "Crush",
    description: "Heart 5 drinks.",
    flavorText: "It's getting serious.",
    category: "novice",
    tier: 1,
    icon: "💌",
    condition: { metric: "hearts_given", threshold: 5 },
  },
  {
    id: "heart_2",
    name: "Lover",
    description: "Heart 20 drinks.",
    flavorText: "You have a big heart.",
    category: "explorer",
    tier: 2,
    icon: "💝",
    condition: { metric: "hearts_given", threshold: 20 },
  },
  {
    id: "heart_3",
    name: "Polyamorous",
    description: "Heart 50 drinks.",
    flavorText: "It's okay to love them all.",
    category: "master",
    tier: 3,
    icon: "💖",
    condition: { metric: "hearts_given", threshold: 50 },
  },
  {
    id: "heart_4",
    name: "Collector",
    description: "Heart 100 drinks.",
    flavorText: "Gotta catch 'em all.",
    category: "grind",
    tier: 4,
    icon: "💘",
    condition: { metric: "hearts_given", threshold: 100 },
  },

  // ==========================================
  // SCREEN TIME / META
  // ==========================================
  {
    id: "badge_badge",
    name: "Badge Badge",
    description: "Unlock 1 Cheevo.",
    flavorText: "Yo dawg, I heard you like badges.",
    category: "grind",
    tier: 1,
    icon: "📛",
    condition: { metric: "cheevos_unlocked", threshold: 1 },
  },
  {
    id: "badge_collector",
    name: "Trophy Case",
    description: "Unlock 10 Cheevos.",
    flavorText: "Starting a collection.",
    category: "grind",
    tier: 2,
    icon: "🏆",
    condition: { metric: "cheevos_unlocked", threshold: 10 },
  },

  {
    id: "time_1",
    name: "Lingerer",
    description: "Spend 1 hour in the app.",
    flavorText: "Finding the perfect drink takes time.",
    category: "novice",
    tier: 1,
    icon: "⏱️",
    condition: { metric: "screen_time_hours", threshold: 1 },
  },
  {
    id: "time_2",
    name: "Researcher",
    description: "Spend 5 hours in the app.",
    flavorText: "Is this for a thesis?",
    category: "explorer",
    tier: 2,
    icon: "🕰️",
    condition: { metric: "screen_time_hours", threshold: 5 },
  },
  {
    id: "time_3",
    name: "Dedication",
    description: "Spend 24 hours in the app.",
    flavorText: "A full day of mixology.",
    category: "master",
    tier: 3,
    icon: "📆",
    condition: { metric: "screen_time_hours", threshold: 24 },
  },
  {
    id: "time_4",
    name: "Addict",
    description: "Spend 100 hours in the app.",
    flavorText: "Go outside. Or to a bar.",
    category: "grind",
    tier: 4,
    icon: "🧟",
    condition: { metric: "screen_time_hours", threshold: 100 },
  },

  // ==========================================
  // HIDDEN / QUIRKY
  // ==========================================
  {
    id: "night_owl",
    name: "Night Owl",
    description: "Use the app between 3 AM and 5 AM.",
    flavorText: "Nothing good happens after 2 AM. Except this.",
    category: "hidden",
    isHidden: true,
    icon: "🦉",
  },
  {
    id: "early_bird",
    name: "Hair of the Dog",
    description: "Use the app between 6 AM and 9 AM.",
    flavorText: "Breakfast of champions.",
    category: "hidden",
    isHidden: true,
    icon: "🐓",
  },
  {
    id: "perfectionist",
    name: "Perfectionist",
    description: "View a recipe you have a 100% match for.",
    flavorText: "Destiny calls.",
    category: "hidden",
    isHidden: true,
    icon: "✨",
  },
  {
    id: "window_licker",
    name: "Dreamer",
    description: "View a recipe you have 0% match for.",
    flavorText: "One day...",
    category: "hidden",
    isHidden: true,
    icon: "🪟",
  },
  {
    id: "shot_taker",
    name: "Shot Taker",
    description: "Prep a recipe with 'shot' in the name.",
    flavorText: "Bottoms up.",
    category: "hidden",
    isHidden: true,
    icon: "🥃",
  },
  {
    id: "metric_system",
    name: "Euro Trip",
    description: "Switch to Metric units.",
    flavorText: "Royale with Cheese.",
    category: "hidden",
    isHidden: true,
    icon: "🇪🇺",
  },
  {
    id: "imperial_march",
    name: "Freedom Units",
    description: "Switch to Imperial units.",
    flavorText: "By the foot.",
    category: "hidden",
    isHidden: true,
    icon: "🦅",
  },
];

export const ACHIEVEMENT_CATEGORIES = {
  novice: { label: "Novice", color: "text-green-500" },
  explorer: { label: "Explorer", color: "text-blue-500" },
  master: { label: "Master", color: "text-purple-500" },
  social: { label: "Social", color: "text-pink-500" },
  grind: { label: "Grind", color: "text-yellow-500" },
  hidden: { label: "Secret", color: "text-gray-500" },
};
